name: flutter_application_1
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase: ^9.0.3
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  go_router: ^14.3.0
  intl: ^0.19.0
  firebase_messaging: ^15.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

