// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-77JOKZQfnBmPpRVwqOHt1udKxsktMI',
    appId: '1:298634593381:web:7357bddbfb6e3cc3ca728c',
    messagingSenderId: '298634593381',
    projectId: 'ait-edu-98b3e',
    authDomain: 'ait-edu-98b3e.firebaseapp.com',
    storageBucket: 'ait-edu-98b3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDWruTR66GDBnZR1SjXhVnQ6uPpllDFf4',
    appId: '1:298634593381:android:89d355281c88b1acca728c',
    messagingSenderId: '298634593381',
    projectId: 'ait-edu-98b3e',
    storageBucket: 'ait-edu-98b3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbFmQ2uPNLWhjrdGQOef7OXMAASv0VmPM',
    appId: '1:298634593381:ios:7ba0b8558ad7edbcca728c',
    messagingSenderId: '298634593381',
    projectId: 'ait-edu-98b3e',
    storageBucket: 'ait-edu-98b3e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbFmQ2uPNLWhjrdGQOef7OXMAASv0VmPM',
    appId: '1:298634593381:ios:7ba0b8558ad7edbcca728c',
    messagingSenderId: '298634593381',
    projectId: 'ait-edu-98b3e',
    storageBucket: 'ait-edu-98b3e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa-77JOKZQfnBmPpRVwqOHt1udKxsktMI',
    appId: '1:298634593381:web:820c69a77b1b12ddca728c',
    messagingSenderId: '298634593381',
    projectId: 'ait-edu-98b3e',
    authDomain: 'ait-edu-98b3e.firebaseapp.com',
    storageBucket: 'ait-edu-98b3e.firebasestorage.app',
  );

}